services:

  postgres:
    image: 'postgres:14.5'
    restart: always
    container_name: go-movies
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd123
      POSTGRES_DB: movies
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - go_movies_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  go_movies_data: